services:
  db:
    image: mariadb
    environment:
      MARIADB_DATABASE: pega
      MARIADB_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./database/docker-mariadb.cnf:/etc/mysql/conf.d./docker-mariadb.cnf

volumes:
  db-data:
